version: '3.9'

services:
  cache:
    image: redis:alpine3.18
    restart: always
    volumes:
      - cache:/data
    command: redis-server --save 20 1 --loglevel warning
    network_mode: host
  db:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - ./seeder/01-ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql
      - ./seeder/02-couriers-seed.sql:/docker-entrypoint-initdb.d/02-couriers-seed.sql
      - ./seeder/03-categories-seed.sql:/docker-entrypoint-initdb.d/03-categories-seed.sql
      - ./seeder/04-promotions-seed.sql:/docker-entrypoint-initdb.d/04-promotions-seed.sql
      - ./seeder/05-products_202311280754.sql:/docker-entrypoint-initdb.d/05-products_202311280754.sql
      - ./seeder/06-product_photos_202311270741.sql:/docker-entrypoint-initdb.d/06-product_photos_202311270741.sql
      - ./seeder/07-variant_groups_202311270741.sql:/docker-entrypoint-initdb.d/07-variant_groups_202311270741.sql
      - ./seeder/08-variant_types_202311270741.sql:/docker-entrypoint-initdb.d/08-variant_types_202311270741.sql
      - ./seeder/09-variant_combinations_202311270741.sql:/docker-entrypoint-initdb.d/09-variant_combinations_202311270741.sql
      - ./seeder/10-variant_combination_products_202311270741.sql:/docker-entrypoint-initdb.d/10-variant_combination_products_202311270741.sql
      - ./seeder/11-addresses_202311280032.sql:/docker-entrypoint-initdb.d/11-addresses_202311280032.sql
      - ./seeder/12-carts_202311280033.sql:/docker-entrypoint-initdb.d/12-carts_202311280033.sql
      - ./seeder/13-merchants_202311280032.sql:/docker-entrypoint-initdb.d/13-merchants_202311280032.sql
      - ./seeder/14-order_detail_products_202311280032.sql:/docker-entrypoint-initdb.d/14-order_detail_products_202311280032.sql
      - ./seeder/15-order_details_202311280032.sql:/docker-entrypoint-initdb.d/15-order_details_202311280032.sql
      - ./seeder/16-orders_202311280031.sql:/docker-entrypoint-initdb.d/16-orders_202311280031.sql
      - ./seeder/17-payments_202311280031.sql:/docker-entrypoint-initdb.d/17-payments_202311280031.sql
      - ./seeder/18-product_photo_orders_202311280033.sql:/docker-entrypoint-initdb.d/18-product_photo_orders_202311280033.sql
      - ./seeder/19-transactions_202311280033.sql:/docker-entrypoint-initdb.d/19-transactions_202311280033.sql
      - ./seeder/20-users_202311280030.sql:/docker-entrypoint-initdb.d/20-users_202311280030.sql
      - ./seeder/21-wallets_202311280031.sql:/docker-entrypoint-initdb.d/21-wallets_202311280031.sql
      - ./seeder/22-sequence-restart.sql:/docker-entrypoint-initdb.d/22-sequence-restart.sql
      - data-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    network_mode: host

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    image: platypusadmin/platypus-be
    restart: always
    env_file:
      - ./be/.env
    depends_on:
      - db
      - cache
    network_mode: host

  platypus-marketplace:
    build:
      context: ./fe/platypus-marketplace
      dockerfile: Dockerfile
    image: platypusadmin/platypus-fe
    restart: always
    network_mode: host

  reverse-proxy:
    depends_on:
      - backend
      - platypus-marketplace
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: host

volumes:
  data-db:
  cache:
